baseURL = "https://thewoood.github.io/"
languageCode = "en-us"
title = "The Woood! Get Envolved..."
theme="archie"
copyright = "© thewoood"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	# subtitle = "[Stuff about Computer Science](https://github.com/athul/archie)"
	subtitle = "Stuff about Computer Science"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/thewoood/"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "Telegram"
# icon = "telegram"
# url = "https://t.me/thewoood"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

